server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: stock-api-gateway
  cloud:
    gateway:
      routes:
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock-service/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category-service/**
